# for checking222333
name: Commit name check
run-name: ${{ github.actor }} is checking name of the commit ${{ github.event.name }}

on:
  push:
    tags-ignore:
      - "v*"
    branches: ['*']

  workflow_dispatch:
  pull_request:
  workflow_call:
  

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Setting up the system
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installing dependencies
        run: npm ci

      - name: Installing commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: Validating recent commit name (conventional commits rules)
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validating pull request commit name (conventional commits rules)
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
