name: Deployment

on:
  push:
    tags: ['v*']
    branches: ['release-v*']
  workflow_dispatch:

jobs:
  unit-tests:
    uses: ./.github/workflows/testing.yml

  e2e-tests:
    uses: ./.github/workflows/testinge2e.yml

  commitlint:
    uses: ./.github/workflows/commitname.yml

  eslintandprettier:
    uses: ./.github/workflows/lintandprettier.yml

    
  release:
    name: Making release and issue about it
    needs:
      - unit-tests
      - e2e-tests
      - commitlint
      - eslintandprettier

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Setting up the system
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Output required data
        id: data-output
        run: |
          previousTag=$(git --no-pager tag --sort=creatordate --merged | tail -2 | head -1)
          lastTag=$(git --no-pager tag --merged | tail -1)
          echo "previousTag=${previousTag}" >> $GITHUB_OUTPUT
          echo "lastTag=${lastTag}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%A %d %B %Y %H:%M:%S %:z')" >> $GITHUB_OUTPUT 
      
      - name: Checking whether our tag is the recent one
        run: |
          test "${{ steps.data-output.outputs.previousTag }}" != "${{ steps.data-output.outputs.lastTag }}"

      - if: success()
        name: Creating changelog on success
        id: create-changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-name: ${{ github.ref_name }}
          semver: false

      - if: contains(github.ref, 'tags')
        name: Create new release branch if new release tag is pushed
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-${{ github.ref_name }}'
          sha: '${{ github.event.push.head.sha }}'

      - if: success()
        name: Creating issue about release or updating existing one
        id: create-issue
        uses: JasonEtco/create-an-issue@v2
        env:
          VERSION: ${{ github.ref_name }}
          DATE: ${{ steps.data-output.outputs.date }}
          CHANGELOG: ${{ steps.create-changelog.outputs.changelog }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{ github.actor }}
        with:
          filename: ./.github/ISSUE_TEMPLATE.md
          update_existing: true
          search_existing: all

      - name: Attach link to test results
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.create-issue.outputs.number }}
          body: |
            - Tests results for #${{ github.run_id }} are there: ${{github.server_url}}/${{ github.repository }}/actions/runs/${{github.run_id}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    outputs:
      issue-number: ${{ steps.create-issue.outputs.number }}

  deploy:
    runs-on: ubuntu-latest
    name: Deployment
    needs: release
    env:
      PUBLIC_URL: https://timsxell.github.io/infrastructure-hw/
    steps:
      - name: Setting up the system
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Installing dependencies
        run: npm ci

      - name: Building project
        run: npm run build

      - if: success()
        name: Uploading artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-project
          path: ./build
          retention-days: 30

      - if: success()
        name: Publishing to gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add deploy link
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ needs.release.outputs.issue-number }}
          body: |
            - Deploy #${{ github.run_id }} is available at ${{ env.PUBLIC_URL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Close the issue of the current release
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ needs.release.outputs.issue-number }}
          comment: |
            - Release done. Closing the issue
