#there will be some workflow

name: Testing
run-name: ${{ github.actor }} is running tests on ${{ github.repository }}

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Setting up the system
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installing node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Installing dependencies
        run: npm ci


